"""type 추가

Revision ID: d6fbf9b1fcbb
Revises: 9df4d603b2ef
Create Date: 2025-02-21 19:22:33.914378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fbf9b1fcbb'
down_revision: Union[str, None] = '9df4d603b2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('disease_details_disease_id_fkey', 'disease_details', type_='foreignkey')
    op.create_foreign_key(None, 'disease_details', 'diseases', ['disease_id'], ['id'], ondelete='CASCADE')
    op.add_column('diseases', sa.Column('type', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_diseases_type'), 'diseases', ['type'], unique=False)
    op.drop_constraint('hospitals_disease_id_fkey', 'hospitals', type_='foreignkey')
    op.create_foreign_key(None, 'hospitals', 'diseases', ['disease_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('insurances_disease_id_fkey', 'insurances', type_='foreignkey')
    op.create_foreign_key(None, 'insurances', 'diseases', ['disease_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insurances', type_='foreignkey')
    op.create_foreign_key('insurances_disease_id_fkey', 'insurances', 'diseases', ['disease_id'], ['id'])
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    op.create_foreign_key('hospitals_disease_id_fkey', 'hospitals', 'diseases', ['disease_id'], ['id'])
    op.drop_index(op.f('ix_diseases_type'), table_name='diseases')
    op.drop_column('diseases', 'type')
    op.drop_constraint(None, 'disease_details', type_='foreignkey')
    op.create_foreign_key('disease_details_disease_id_fkey', 'disease_details', 'diseases', ['disease_id'], ['id'])
    # ### end Alembic commands ###
